version: 2.1

executors:
  android:
    docker:
      - image: cimg/android:30.0
    resource_class: xlarge

orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    executor: android
    steps:
      - checkout
      - ruby/install:
          version: '3.0.1'
      - run: cd android
      - ruby/install-deps
