version: 2.1

executors:
  android:
    docker:
      - image: cimg/android:30.0
    resource_class: xlarge
  mac:
    macos:
      xcode: 12.5.0

orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  beta_android:
    executor: android
    steps:
      - checkout

  beta_ios:
    executor: mac
    steps:
      - checkout
      - restore_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
      - run: 
          command: bundle install
          working_directory: ios
      - save_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

workflows:
  beta:
    jobs:
      - beta_android
      - beta_ios
