version: 2.1

executors:
  android:
    docker:
      - image: cimg/android:30.0
    resource_class: xlarge
  mac:
    macos:
      xcode: 12.5.0

orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  beta_android:
    executor: android
    steps:
      - checkout
      - run: ruby --version

  beta_ios:
    executor: mac
    steps:
      - checkout
      - run:
          name: Set Ruby Version
          command: echo 'chruby system' >> ~/.bash_profile
      - run: ruby --version

workflows:
  beta:
    jobs:
      - beta_android
      - beta_ios
