version: 2.1

orbs:
  android: circleci/android@1.0.3

executors:
  mac:
    macos:
      xcode: 12.5.0

jobs:
  beta_android:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - restore_cache:
          key: bundle-v1-{{ checksum "android/Gemfile.lock" }}
      - run: 
          command: bundle install
          working_directory: android
      - save_cache:
          key: bundle-v1-{{ checksum "android/Gemfile.lock" }}
          paths:
            - android/vendor/bundle
      - run:
          command: bundle exec fastlane beta
          working_directory: android

  beta_ios:
    executor: mac
    steps:
      - checkout
      - restore_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}
      - run: 
          command: bundle install
          working_directory: ios
      - save_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}
          paths:
            - ios/vendor/bundle
      - run:
          command: bundle exec fastlane beta
          working_directory: ios

workflows:
  beta:
    jobs:
      - beta_android
      - beta_ios
